server {
  listen 80;
  server_name morjachka.ru www.morjachka.ru;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name morjachka.ru www.morjachka.ru;

  ssl_certificate /etc/letsencrypt/live/morjachka.ru/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/morjachka.ru/privkey.pem;

  client_max_body_size 10M;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    
    # Routes
    try_files $uri $uri/ /index.html;
  }

  # Proxy
  location /api/ {
    proxy_pass http://backend:7000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # Certbot
  location /.well-known/acme-challenge/ {
  root /var/www/certbot;
  }
}