# server {
#   listen 80;
#   server_name morjachka.ru;

#   client_max_body_size 10M;

#   # Certbot
#   location /.well-known/acme-challenge/ {
#     root /var/www/certbot;
#   }

#   location / {
#     root /usr/share/nginx/html;
#     index index.html;
    
#     # Routes
#     try_files $uri $uri/ /index.html;
#   }

#   # Proxy
#   location /api/ {
#     proxy_pass http://backend:7000;
#     proxy_set_header Host $host;
#     proxy_set_header X-Real-IP $remote_addr;
#     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#   }

# #   return 301 https://$host$request_uri;
# }

# # server {
# #   listen 443 ssl;
# #   server_name morjachka.ru;

# #   ssl_certificate /etc/letsencrypt/live/morjachka.ru/fullchain.pem;
# #   ssl_certificate_key /etc/letsencrypt/live/morjachka.ru/privkey.pem;

# #   client_max_body_size 10M;

# #   location / {
# #     root /usr/share/nginx/html;
# #     index index.html;
    
# #     # Routes
# #     try_files $uri $uri/ /index.html;
# #   }

# #   # Proxy
# #   location /api/ {
# #     proxy_pass http://backend:7000;
# #     proxy_set_header Host $host;
# #     proxy_set_header X-Real-IP $remote_addr;
# #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
# #   }

# #   # Certbot
# #   location /.well-known/acme-challenge/ {
# #     root /var/www/certbot;
# #   }
# # }

server {
  listen 80;
  server_name morjachka.ru;

  # Certbot
  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  # Redirect
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  server_name morjachka.ru;

  ssl_certificate /etc/letsencrypt/live/morjachka.ru/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/morjachka.ru/privkey.pem;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
  ssl_prefer_server_ciphers off;

  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

  client_max_body_size 10M;

  # Pages
  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  # Proxy
  location /api/ {
    proxy_pass http://backend:7000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
